articulos/urls.py
from django.urls import path
from .views import Lista, comprar

app_name = 'articulos'

urlpatterns = [
    path('lista/', Lista.as_view(), name='lista'),
    path('comprar/<int:pk>', comprar, name='comprar'),

]

hospital/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pacientes/' , include('pacientes.urls')),
    path('usuarios/' , include('usuarios.urls')),
    path('' , include('usuarios.urls')),
    path('articulos/' , include('articulos.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

articulos/models.py
from django.db import models

class Articulo(models.Model):
    clave = models.CharField("Clave", max_length=30)
    nombre = models.CharField("Artículo", max_length=150)
    descripcion = models.CharField("Descripción", max_length=300, blank=True, null=True)
    imgen = models.ImageField("Imágen", upload_to="articulos")
    precio = models.DecimalField("Precio unitario", max_digits=8, decimal_places=2)
    stock = models.IntegerField("Unidades")
    categoria = models.ForeignKey("articulos.Categoria", verbose_name="Categoría", on_delete=models.DO_NOTHING)

    def __str__(self):
        return self.nombre
    

class Categoria(models.Model):
    nombre = models.CharField("Categoría", max_length=100)

    def __str__(self):
        return self.nombre
    


# class Venta(models.Model):
#     fecha 
#     usuario 


# class DetalleVenta(models.Model):
#     articulo = models.ForeignKey("articulos.Articulo", verbose_name="Articulo", on_delete=models.CASCADE)
#     venta = models.ForeignKey("articulos.Venta", verbose_name=_(""), on_delete=models.CASCADE)
    

articulos/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic.list import ListView
from .models import Articulo
from django.contrib.auth.mixins import PermissionRequiredMixin, LoginRequiredMixin, AccessMixin


class Lista(LoginRequiredMixin, ListView):
    model = Articulo
    paginate_by = 5

def comprar(request, pk):
    articulo = get_object_or_404(Articulo, pk=pk)
    if articulo.stock > 0:
        articulo.stock = articulo.stock - 1
        articulo.save()

        id = str(pk)

        request.session['total'] = request.session['total'] + float(articulo.precio)
        request.session['cuantos'] = request.session['cuantos'] + 1

        if id in request.session['articulos']:
            request.session['articulos'][id]['cantidad'] = request.session['articulos'][id]['cantidad'] + 1
        else:
            request.session['articulos'][id] = {'precio':float(articulo.precio), 'cantidad': 1}

        
    
    print(request.session['articulos'])

    return redirect('articulos:lista')

articulos/templates/articulos/articulo_list.html
{% extends 'base.html' %}

{% block titulo %}Lista de artículos{% endblock titulo %}
    
{% block contenido %}
<h1>Lista de Artículos</h1>
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Clave</th>
            <th>Artículo</th>
            <th>Precio</th>
            <th>Existencia</th>
            <th>Opciones</th>
        </tr>
    </thead>
    <tbody>
        {% for articulo in object_list %}
        <tr>
            <td>{{articulo.clave}}</td>
            <td>{{articulo.nombre}}</td>
            <td>${{articulo.precio}}</td>
            <td>{{articulo.stock}}</td>
            <td>
                
                {% if articulo.stock > 0 %}
                    <a title="Comprar" class="btn btn-warning" href="{% url 'articulos:comprar' articulo.id %}">
                        <i class="fas fa-cart-arrow-down"></i>
                    </a>
                {% else %}
                    <div class="alert alert-warning">Producto agotado</div>
                {% endif %}
                    
                <a title="Elimina paciente" class="btn btn-danger" href="">
                    <i class="far fa-trash-alt"></i>
                </a>
            </td>
        </tr>
        {% endfor %}
    </tbody>
</table>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
            <a href="?page={{ page_obj.next_page_number }}">next</a>
            <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>


{% endblock contenido %}
    